# Generated by Django 3.1.3 on 2022-06-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course_id',
            new_name='course',
        ),
    ]
